import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReduxProvider from "./providers/ReduxProvider";
import { Toaster } from "react-hot-toast";
import InitializeAuth from "./Components/InitializeAuth/InitializeAuth";
import { ModalProvider } from "@/context/ModalContext";
import GlobalModal from "./Components/GlobalModal";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Abdullah and Fatima",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Comic+Neue:wght@300;400;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster
          position="top-center"
          reverseOrder={false}
          toastOptions={{
            duration: 1500,
          }}
        />
        <ReduxProvider>
          <InitializeAuth />
          <ModalProvider>
            <Suspense>
            <GlobalModal />
            </Suspense>
            {children}
          </ModalProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
