export const booksData = [
  {
    slug: "fatima-s-first-fast",
    title: "Fatima’s First Fast",
    tagline:
      "She’s little. She’s determined. But can she make it till Maghrib?",
    isbn: "978-1-918105-62-9",
    age_group: "5 - 8",
    price_gbp: 6.99,
    format: "Paper Back",
    series: "Abdullah and Fatima",
    product_url: "https://shop.sidr.productions/products/fatima-s-first-fast",
    overview:
      "Fatima is trying her first ever fast during Ramadan — and she’s beyond excited. But as the hours pass and her tummy rumbles, will she be able to keep going? A touching introduction to the spirit of Ramadan, patience, and the joy of growing up with faith.",
    learning_notes: "",
    islamic_references: "",
    for_parents_teachers: "",
    cover_image:
      "https://shop.sidr.productions/cdn/shop/files/Book1_Fatima_sFirstFast-BookCover_1__page-0001.jpg?v=1762836751&width=330",
    pages: [],
  },
  {
    slug: "the-day-we-almost-missed-salah",
    title: "The Day We Almost Missed Salah",
    tagline: "Can a fun day turn into a race against time… for Salah?",
    isbn: "978-1-918105-61-2",
    age_group: "5 - 8",
    price_gbp: 6.99,
    format: "Paper Back",
    series: "Abdullah and Fatima",
    product_url:
      "https://shop.sidr.productions/products/the-day-we-almost-missed-salah",
    overview:
      "Abdullah and Fatima are having the best day — until they suddenly realize… it’s prayer time! What follows is a lesson in urgency, prioritization, and the beauty of Salah at its proper time. This relatable story gently reminds kids that no matter how busy or distracted we get, prayer is always worth stopping for.",
    learning_notes: "",
    islamic_references: "",
    for_parents_teachers: "",
    cover_image:
      "https://shop.sidr.productions/cdn/shop/files/TheDayWeAlmostMissedSalah.png?v=1762849172&width=330",
    pages: [],
  },
  {
    slug: "the-iftar-delivery-mission",
    title: "The Iftar Delivery Mission",
    tagline: "Ramadan isn’t just about fasting… it’s about giving too.",
    isbn: "978-1-918105-67-4",
    age_group: "5 - 8",
    price_gbp: 6.99,
    format: "Paper Back",
    series: "Abdullah and Fatima",
    product_url:
      "https://shop.sidr.productions/products/the-iftar-delivery-mission",
    overview:
      "Abdullah and Fatima team up with Baba for a special iftar delivery — but unexpected surprises are waiting along the way! Join them on this heartwarming mission that celebrates community, charity, and the blessings of Ramadan.",
    learning_notes: "",
    islamic_references: "",
    for_parents_teachers: "",
    cover_image:
      "https://shop.sidr.productions/cdn/shop/files/TheIftarDeliveryMission.png?v=1762850477&width=330",
    pages: [],
  },
  {
    slug: "fatima-and-the-furry-friend",
    title: "Fatima and the Furry Friend",
    tagline: "A lost kitten. A big heart. And an even bigger lesson.",
    isbn: "978-1-918105-65-0",
    age_group: "5 - 8",
    price_gbp: 6.99,
    format: "Paper Back",
    series: "Abdullah and Fatima",
    product_url:
      "https://shop.sidr.productions/products/fatima-and-the-furry-friend",
    overview:
      "Fatima finds a scared, shivering kitten near the masjid. She wants to help — but what should they do next? Through this gentle tale, children learn about mercy towards animals and why kindness is always the right choice, even when it’s not easy.",
    learning_notes: "",
    islamic_references: "",
    for_parents_teachers: "",
    cover_image:
      "https://shop.sidr.productions/cdn/shop/files/Fatima_sFurryFriend.png?v=1762840568&width=330",
    pages: [],
  },
  {
    slug: "the-kindness-jar",
    title: "The Kindness Jar",
    tagline: "One little jar. Countless acts of kindness. Big rewards!",
    isbn: "978-1-918105-63-6",
    age_group: "5 - 8",
    price_gbp: 6.99,
    format: "Paper Back",
    series: "Abdullah and Fatima",
    product_url: "https://shop.sidr.productions/products/the-kindness-jar",
    overview:
      "When Mama brings out an empty jar and says it’s time to fill it with kindness, Abdullah and Fatima begin to see their world differently. Small good deeds, loving words, and selfless actions — every act goes into the jar! But what will happen when the jar is full?",
    learning_notes: "",
    islamic_references: "",
    for_parents_teachers: "",
    cover_image:
      "https://shop.sidr.productions/cdn/shop/files/TheKindnessJar.png?v=1762850504&width=330",
    pages: [],
  },
  {
    slug: "the-forgotten-salam",
    title: "The Forgotten Salam",
    tagline: "What happens when we forget a single, powerful word?",
    isbn: "978-1-918105-64-3",
    age_group: "5 - 8",
    price_gbp: 6.99,
    format: "Paper Back",
    series: "Abdullah and Fatima",
    product_url: "https://shop.sidr.productions/products/the-forgotten-salam",
    overview:
      "Abdullah rushes into class without saying “Salam” — and suddenly everything feels… off. This charming story explores the significance of Islamic greetings and how the simple word “Salam” can change our day and connect hearts in a beautiful way.",
    learning_notes: "",
    islamic_references: "",
    for_parents_teachers: "",
    cover_image:
      "https://shop.sidr.productions/cdn/shop/files/TheForgottenIslamFrontCover.png?v=1762839642&width=330",
    pages: [],
  },
  {
    slug: "abdullah-s-angry-day",
    title: "Abdullah’s Angry Day",
    tagline: "Some days are tough. But does anger have to win?",
    isbn: "978-1-918105-66-7",
    age_group: "5 - 8",
    price_gbp: 6.99,
    format: "Paper Back",
    series: "Abdullah and Fatima",
    product_url: "https://shop.sidr.productions/products/abdullah-s-angry-day",
    overview:
      "Abdullah’s having one of those days — from spilled juice to a broken toy, everything feels frustrating. Will he let his anger control him, or will he remember what the Prophet(P.B.U.H) taught us about patience and emotional strength?",
    learning_notes: "",
    islamic_references: "",
    for_parents_teachers: "",
    cover_image:
      "https://shop.sidr.productions/cdn/shop/files/Abdullah_sAngryDay.png?v=1762849075&width=330",
    pages: [],
  },
  {
    slug: "fatima-s-shiny-shoes",
    title: "Fatima’s Shiny Shoes",
    tagline:
      "They sparkle. They shine. But will they make Fatima feel full inside?",
    isbn: "978-1-918105-68-1",
    age_group: "5 - 8",
    price_gbp: 9.99,
    format: "Paper Back",
    series: "Abdullah and Fatima",
    product_url: "https://shop.sidr.productions/products/fatima-s-shiny-shoes",
    overview:
      "Fatima loves her new shoes — until she sees someone with none. A powerful story about gratitude, humility, and the joy of giving something precious for the sake of Allah.",
    learning_notes: "",
    islamic_references: "",
    for_parents_teachers: "",
    cover_image:
      "https://shop.sidr.productions/cdn/shop/files/Fatima_sShinyShoes.png?v=1762856781&width=330",
    pages: [],
  },
  {
    slug: "the-eid-surprise",
    title: "The Eid Surprise",
    tagline:
      "A joyful Eid tale about anticipation, family and sharing happiness.",
    isbn: "978-1-918105-69-8",
    age_group: "5 - 8",
    price_gbp: 6.99,
    format: "Paper Back",
    series: "Abdullah and Fatima",
    product_url: "https://shop.sidr.productions/products/the-eid-surprise",
    overview:
      "The Eid Surprise” is a heartwarming children’s story that celebrates the joy, anticipation, and togetherness of Eid. Through engaging storytelling and delightful illustrations, young readers join the characters as they prepare for the big day — from decorating and giving gifts to sharing special moments with family. The book beautifully captures the true spirit of Eid, teaching children about kindness, gratitude, and the happiness that comes from sharing and caring for others. Perfect for early readers, this book helps families introduce Islamic values in a fun and memorable way.",
    learning_notes: "",
    islamic_references: "",
    for_parents_teachers: "",
    cover_image:
      "https://shop.sidr.productions/cdn/shop/files/TheEidSurprise.png?v=1762850359&width=330",
    pages: [],
  },
  {
    slug: "the-midnight-visitor",
    title: "The Midnight Visitor",
    tagline: "A cosy bedtime story about facing night-time fears with faith.",
    isbn: "978-1-918105-70-4",
    age_group: "5 - 8",
    price_gbp: 6.99,
    format: "Paper Back",
    series: "Abdullah and Fatima",
    product_url: "https://shop.sidr.productions/products/the-midnight-visitor",
    overview:
      "The Midnight Fright is a comforting bedtime story from the beloved Abdullah & Fatima series that helps children overcome their fears through faith. When a loud thunderstorm wakes the siblings in the middle of the night, their father gently reminds them of the Prophet Muhammad (P.B.U.H) and his unwavering trust in Allah during moments of fear. Through heartwarming dialogue and beautiful illustrations, this story teaches children the power of tawakkul (trust in Allah), dhikr (remembrance of Allah), and finding peace in prayer. A perfect read to soothe young hearts and strengthen faith before bedtime.",
    learning_notes: "",
    islamic_references: "",
    for_parents_teachers: "",
    cover_image:
      "https://shop.sidr.productions/cdn/shop/files/TheMidnightFright.png?v=1762848957&width=330",
    pages: [],
  },
  {
    slug: "the-lost-quran-page",
    title: "The Lost Quran Page",
    tagline:
      "A gentle lesson about honesty, the Qur’an and seeking forgiveness.",
    isbn: "978-1-918105-71-1",
    age_group: "5 - 8",
    price_gbp: 6.99,
    format: "Paper Back",
    series: "Abdullah and Fatima",
    product_url: "https://shop.sidr.productions/products/the-lost-quran-page",
    overview:
      "The Lost Quran Page is a touching story from the Abdullah & Fatima series that teaches children the importance of honesty, respect for the Holy Quran, and seeking forgiveness from Allah. When Abdullah accidentally tears a page from his Quran, he feels scared and hides his mistake. But through his parents’ gentle guidance, he learns that admitting mistakes and asking for forgiveness makes us stronger in faith. Beautifully illustrated and written with warmth, this story helps young readers understand the value of truth, repentance, and love for the Quran — inspiring them to protect and cherish Allah’s words in their everyday lives.",
    learning_notes: "",
    islamic_references: "",
    for_parents_teachers: "",
    cover_image:
      "https://shop.sidr.productions/cdn/shop/files/TheLostQuranPage_ab077a3a-75fb-41ec-9610-2bcb34b1b76c.png?v=1762850299&width=330",
    pages: [],
  },
  {
    slug: "the-masjid-race",
    title: "The Masjid Race",
    tagline:
      "A fun race to the masjid that shows what real winning looks like.",
    isbn: "978-1-918105-72-8",
    age_group: "5 - 8",
    price_gbp: 6.99,
    format: "Paper Back",
    series: "Abdullah and Fatima",
    product_url: "https://shop.sidr.productions/products/the-masjid-race",
    overview:
      "In The Masjid Race, Abdullah and Fatima set off on an exciting challenge with their Baba — to see who can reach the masjid first! Along the way, they learn that true victory isn’t just about winning the race, but about the joy of going to the masjid and the blessings that come with it. Filled with cheerful illustrations and heartfelt lessons, this story inspires children to love visiting the masjid, value family time, and understand the beauty of doing good deeds for Allah. Written by Dr. Nousheen Zakaria and illustrated by Sidr Productions, The Masjid Race is a delightful reminder that faith, fun, and family make the best team.",
    learning_notes: "",
    islamic_references: "",
    for_parents_teachers: "",
    cover_image:
      "https://shop.sidr.productions/cdn/shop/files/TheMasjidRace.png?v=1762849899&width=330",
    pages: [],
  },
];
