export const booksData = [
  {
    slug: "fatima-s-first-fast",
    title: "Fatima’s First Fast",
    tagline:
      "She’s little. She’s determined. But can she make it till Maghrib?",
    isbn: "978-1-918105-62-9",
    age_group: "5 - 8",
    price_gbp: 6.99,
    format: "Paper Back",
    series: "Abdullah and Fatima",
    product_url: "https://shop.sidr.productions/products/fatima-s-first-fast",
    overview: "",
    learning_notes: "",
    islamic_references: "",
    for_parents_teachers: "",
    cover_image:
      "https://shop.sidr.productions/cdn/shop/files/Book1_Fatima_sFirstFast-BookCover_1__page-0001.jpg?v=1762836751&width=330",
    pages: [],
  },
  {
    slug: "the-day-we-almost-missed-salah",
    title: "The Day We Almost Missed Salah",
    tagline: "Can a fun day turn into a race against time… for Salah?",
    isbn: "978-1-918105-61-2",
    age_group: "5 - 8",
    price_gbp: 6.99,
    format: "Paper Back",
    series: "Abdullah and Fatima",
    product_url:
      "https://shop.sidr.productions/products/the-day-we-almost-missed-salah",
    overview: "",
    learning_notes: "",
    islamic_references: "",
    for_parents_teachers: "",
    cover_image:
      "https://shop.sidr.productions/cdn/shop/files/TheDayWeAlmostMissedSalah.png?v=1762849172&width=330",
    pages: [],
  },
  {
    slug: "the-iftar-delivery-mission",
    title: "The Iftar Delivery Mission",
    tagline: "Ramadan isn’t just about fasting… it’s about giving too.",
    isbn: "978-1-918105-67-4",
    age_group: "5 - 8",
    price_gbp: 6.99,
    format: "Paper Back",
    series: "Abdullah and Fatima",
    product_url:
      "https://shop.sidr.productions/products/the-iftar-delivery-mission",
    overview: "",
    learning_notes: "",
    islamic_references: "",
    for_parents_teachers: "",
    cover_image:
      "https://shop.sidr.productions/cdn/shop/files/TheIftarDeliveryMission.png?v=1762850477&width=330",
    pages: [],
  },
  {
    slug: "fatima-and-the-furry-friend",
    title: "Fatima and the Furry Friend",
    tagline: "A lost kitten. A big heart. And an even bigger lesson.",
    isbn: "978-1-918105-65-0",
    age_group: "5 - 8",
    price_gbp: 6.99,
    format: "Paper Back",
    series: "Abdullah and Fatima",
    product_url:
      "https://shop.sidr.productions/products/fatima-and-the-furry-friend",
    overview: "",
    learning_notes: "",
    islamic_references: "",
    for_parents_teachers: "",
    cover_image:
      "https://shop.sidr.productions/cdn/shop/files/Fatima_sFurryFriend.png?v=1762840568&width=330",
    pages: [],
  },
  {
    slug: "the-kindness-jar",
    title: "The Kindness Jar",
    tagline: "One little jar. Countless acts of kindness. Big rewards!",
    isbn: "978-1-918105-63-6",
    age_group: "5 - 8",
    price_gbp: 6.99,
    format: "Paper Back",
    series: "Abdullah and Fatima",
    product_url: "https://shop.sidr.productions/products/the-kindness-jar",
    overview: "",
    learning_notes: "",
    islamic_references: "",
    for_parents_teachers: "",
    cover_image:
      "https://shop.sidr.productions/cdn/shop/files/TheKindnessJar.png?v=1762850504&width=330",
    pages: [],
  },
  {
    slug: "the-forgotten-salam",
    title: "The Forgotten Salam",
    tagline: "What happens when we forget a single, powerful word?",
    isbn: "978-1-918105-64-3",
    age_group: "5 - 8",
    price_gbp: 6.99,
    format: "Paper Back",
    series: "Abdullah and Fatima",
    product_url: "https://shop.sidr.productions/products/the-forgotten-salam",
    overview: "",
    learning_notes: "",
    islamic_references: "",
    for_parents_teachers: "",
    cover_image:
      "https://shop.sidr.productions/cdn/shop/files/TheForgottenIslamFrontCover.png?v=1762839642&width=330",
    pages: [],
  },
  {
    slug: "abdullah-s-angry-day",
    title: "Abdullah’s Angry Day",
    tagline: "Some days are tough. But does anger have to win?",
    isbn: "978-1-918105-66-7",
    age_group: "5 - 8",
    price_gbp: 6.99,
    format: "Paper Back",
    series: "Abdullah and Fatima",
    product_url: "https://shop.sidr.productions/products/abdullah-s-angry-day",
    overview: "",
    learning_notes: "",
    islamic_references: "",
    for_parents_teachers: "",
    cover_image:
      "https://shop.sidr.productions/cdn/shop/files/Abdullah_sAngryDay.png?v=1762849075&width=330",
    pages: [],
  },
  {
    slug: "fatima-s-shiny-shoes",
    title: "Fatima’s Shiny Shoes",
    tagline:
      "They sparkle. They shine. But will they make Fatima feel full inside?",
    isbn: "978-1-918105-68-1",
    age_group: "5 - 8",
    price_gbp: 9.99,
    format: "Paper Back",
    series: "Abdullah and Fatima",
    product_url: "https://shop.sidr.productions/products/fatima-s-shiny-shoes",
    overview: "",
    learning_notes: "",
    islamic_references: "",
    for_parents_teachers: "",
    cover_image:
      "https://shop.sidr.productions/cdn/shop/files/Fatima_sShinyShoes.png?v=1762856781&width=330",
    pages: [],
  },
  {
    slug: "the-eid-surprise",
    title: "The Eid Surprise",
    tagline:
      "A joyful Eid tale about anticipation, family and sharing happiness.",
    isbn: "978-1-918105-69-8",
    age_group: "5 - 8",
    price_gbp: 6.99,
    format: "Paper Back",
    series: "Abdullah and Fatima",
    product_url: "https://shop.sidr.productions/products/the-eid-surprise",
    overview: "",
    learning_notes: "",
    islamic_references: "",
    for_parents_teachers: "",
    cover_image:
      "https://shop.sidr.productions/cdn/shop/files/TheEidSurprise.png?v=1762850359&width=330",
    pages: [],
  },
  {
    slug: "the-midnight-visitor",
    title: "The Midnight Visitor",
    tagline: "A cosy bedtime story about facing night-time fears with faith.",
    isbn: "978-1-918105-70-4",
    age_group: "5 - 8",
    price_gbp: 6.99,
    format: "Paper Back",
    series: "Abdullah and Fatima",
    product_url: "https://shop.sidr.productions/products/the-midnight-visitor",
    overview: "",
    learning_notes: "",
    islamic_references: "",
    for_parents_teachers: "",
    cover_image:
      "https://shop.sidr.productions/cdn/shop/files/TheMidnightFright.png?v=1762848957&width=330",
    pages: [],
  },
  {
    slug: "the-lost-quran-page",
    title: "The Lost Quran Page",
    tagline:
      "A gentle lesson about honesty, the Qur’an and seeking forgiveness.",
    isbn: "978-1-918105-71-1",
    age_group: "5 - 8",
    price_gbp: 6.99,
    format: "Paper Back",
    series: "Abdullah and Fatima",
    product_url: "https://shop.sidr.productions/products/the-lost-quran-page",
    overview: "",
    learning_notes: "",
    islamic_references: "",
    for_parents_teachers: "",
    cover_image:
      "https://shop.sidr.productions/cdn/shop/files/TheLostQuranPage_ab077a3a-75fb-41ec-9610-2bcb34b1b76c.png?v=1762850299&width=330",
    pages: [],
  },
  {
    slug: "the-masjid-race",
    title: "The Masjid Race",
    tagline:
      "A fun race to the masjid that shows what real winning looks like.",
    isbn: "978-1-918105-72-8",
    age_group: "5 - 8",
    price_gbp: 6.99,
    format: "Paper Back",
    series: "Abdullah and Fatima",
    product_url: "https://shop.sidr.productions/products/the-masjid-race",
    overview: "",
    learning_notes: "",
    islamic_references: "",
    for_parents_teachers: "",
    cover_image:
      "https://shop.sidr.productions/cdn/shop/files/TheMasjidRace.png?v=1762849899&width=330",
    pages: [],
  },
];
