export const GAMES = [
  {
    id: "g1",
    slug: "abdullah-fatima-adventures",
    title: "Abdullah & Fatima Adventures",
    blurb:
      "Explore, help and learn across connected quests inspired by everyday Muslim life.",
    type: "Story",
    values: ["Sabr", "Adab", "Rahmah"],
    age: "5–12",
    mode: "Story & Mini-quests",
    thumbUrl: "/assets/game-1.jpg",
    platforms: ["Web", "iOS", "Android"],
    url: "https://tourmaline-treacle-839185.netlify.app/",
    premiumUrl: "",
    free: true,
  },
  {
    id: "g2",
    slug: "the-run",
    title: "The Run",
    blurb:
      "Dash, dodge and make quick choices while keeping adab and safety in mind.",
    type: "Runner",
    values: ["Adab", "Amanah"],
    age: "8–12",
    mode: "Endless runner · Levels",
    thumbUrl: "/assets/game-4.jpg",
    platforms: ["Web"],
    url: "https://starlit-dodol-9596c0.netlify.app/",
    premiumUrl: "https://verdant-cocada-8a5ac3.netlify.app/",
  },
  {
    id: "g3",
    slug: "the-escape",
    title: "The Escape",
    blurb: "Practice safe crossing, patience and awareness at a busy junction.",
    type: "Puzzle",
    values: ["Sabr", "Amanah"],
    thumbUrl: "/assets/game-3.jpg",
    age: "5–7",
    mode: "Level-based safety puzzles",
    platforms: ["Web", "Android"],
    url: "https://startling-treacle-fb8a93.netlify.app/",
    premiumUrl: "https://effortless-selkie-b4945c.netlify.app/",
  },
  {
    id: "g3",
    slug: "road-cross",
    title: "Road Cross",
    blurb: "Practice safe crossing, patience and awareness at a busy junction.",
    type: "Puzzle",
    values: ["Sabr", "Amanah"],
    age: "5–7",
    mode: "Level-based safety puzzles",
    platforms: ["Web", "Android"],
    thumbUrl: "/assets/game-2.jpg",
    url: "https://wonderful-rugelach-0d3354.netlify.app/",
    premiumUrl: "https://curious-kulfi-2ef0d8.netlify.app/",
  },
];