// Input.tsx
import { Eye, EyeOff } from "lucide-react";
import { useState } from "react";

const generateIdOrName = ({ label }: any) => {
  return label
    ? label.toLowerCase().replace(/\s+/g, "-")
    : `input-${Math.random().toString(36).substr(2, 9)}`;
};

const Input = ({
  type = "text",
  id,
  name,
  label = "",
  placeholder = "",
  icon,
  tooltip,
  errorMessage,
  smallSize = false,
  topSpace = 0,
  bottomSpace = 0,
  className = "",
  ...props
}: any) => {
  const [isSecureEntry, setIsSecureEntry] = useState(true);

  const autoGeneratedId = id || generateIdOrName({ label });
  const autoGeneratedName = name || generateIdOrName({ label });

  const validTopSpace = Math.min(Math.max(topSpace, 0), 5);
  const validBottomSpace = Math.min(Math.max(bottomSpace, 0), 5);

  return (
    <div
      className={`relative mt-${validTopSpace} mb-${validBottomSpace} ${className}`}
    >
      {label && (
        <label
          htmlFor={autoGeneratedId}
          className="font-comic font-semibold mb-2 block text-lg text-[#444341]"
        >
          {label}
        </label>
      )}

      <div className="relative">
        {/* Left icon */}
        {icon && (
          <span className="absolute left-2 top-1/2 transform -translate-y-1/2 text-gray-500">
            {icon}
          </span>
        )}

        <input
          {...props} // <-- spread register() props here
          type={
            type === "password" ? (isSecureEntry ? "password" : "text") : type
          }
          id={autoGeneratedId}
          name={autoGeneratedName}
          placeholder={placeholder}
          className={`w-full outline-0 border rounded-lg ${
            icon ? "pl-10" : "pl-3"
          } pr-4 ${smallSize ? "py-2" : "py-2"} font-comic font-semibold
            ${errorMessage ? "border-red-500" : "border-gray-400"}`}
        />

        {/* Right tooltip */}
        {tooltip && (
          <span className="absolute right-2 top-1/2 transform -translate-y-1/2 text-gray-500">
            {tooltip}
          </span>
        )}

        {/* Password toggle */}
        {type === "password" && (
          <span
            onClick={() => setIsSecureEntry((prev) => !prev)}
            className="absolute right-4 top-1/2 transform -translate-y-1/2 cursor-pointer"
          >
            {isSecureEntry ? <Eye size={20} /> : <EyeOff size={20} />}
          </span>
        )}
      </div>

      {/* Error message */}
      {errorMessage && (
        <p className="text-red-500 font-semibold text-sm font-comic mt-1">
          {errorMessage}
        </p>
      )}
    </div>
  );
};

export default Input;
