import { Eye, EyeOff } from "lucide-react";
import { useState } from "react";

const generateIdOrName = ({ label }: any) => {
  return label
    ? label.toLowerCase().replace(/\s+/g, "-")
    : `input-${Math.random().toString(36).substr(2, 9)}`;
};
const Input = ({
  value,
  type = "text", // Default type is text
  id, // Optional id, auto-generated if not provided
  name, // Optional name, auto-generated if not provided
  onChange,
  disabled = false, // Default is not disabled
  autoComplete = "off", // Default autocomplete is off
  maxLength,
  required = false, // Default is not required
  label = "",
  placeholder = "", // Placeholder is used for label and placeholder
  topSpace = 0, // Default top margin is 0
  bottomSpace = 0, // Default bottom margin is 0
  className = "",
  min,
  max,
  readOnly = false,
  accept,
  onKeyDown,
  icon,
  tooltip,
  smallSize = false,
}: any) => {
  const [isSecureEntry, setIsSecureEntry] = useState(true);

  const autoGeneratedId = id || generateIdOrName(label);
  const autoGeneratedName = name || generateIdOrName(label);

  const validTopSpace = Math.min(Math.max(topSpace, 0), 5);
  const validBottomSpace = Math.min(Math.max(bottomSpace, 0), 5);

  return (
    <>
      <div
        className={`relative mt-${validTopSpace} mb-${validBottomSpace} ${className}`}
      >
        {label && (
          <label
            htmlFor={autoGeneratedId}
            className="font-comic font-semibold mb-2 block text-lg text-[#444341]"
          >
            {label}
          </label>
        )}

        <div className="relative">
          {/* Left icon */}
          {icon && (
            <span className="absolute left-2 top-1/2 transform -translate-y-1/2 text-gray-500">
              {icon}
            </span>
          )}

          <input
            type={
              type === "password" ? (isSecureEntry ? "password" : "text") : type
            }
            className={`w-full outline-0 border border-gray-400 rounded-lg ${
              icon ? "pl-10" : "pl-3"
            }  pr-4 ${smallSize ? "py-2" : "py-2"} font-comic font-semibold`}
            id={autoGeneratedId}
            name={autoGeneratedName}
            value={value}
            onChange={onChange}
            disabled={disabled}
            autoComplete={autoComplete}
            maxLength={maxLength}
            required={required}
            placeholder={placeholder}
            onKeyDown={onKeyDown}
            accept={accept}
            min={min}
            max={max}
            readOnly={readOnly}
          />

          {/* Right eye icon for password */}
          {tooltip && (
            <span className="absolute right-2 top-1/2 transform -translate-y-1/2 text-gray-500">
              {tooltip}
            </span>
          )}
          {type === "password" && (
            <span
              onClick={() => setIsSecureEntry((prev) => !prev)}
              className="absolute right-4 top-1/2 transform -translate-y-1/2 cursor-pointer"
            >
              {isSecureEntry ? <Eye size={20} /> : <EyeOff size={20} />}
            </span>
          )}
        </div>
      </div>
    </>
  );
};

export default Input;
